{
    'name': 'Hospital Management',
    'version': '1.0',
    'summary': 'Hospital Management',
    'description': 'Module for Managing the hospital',
    'category': 'Extra Tools',
    'author': 'AdesDev',
    'sequence': '0',
    'website': 'https://digitalfarmer.github.io',
    'license': 'AGPL-3',
    'depends': ['base','mail','stock'],
    'data':[
        'views/patient_view.xml',
        'views/appointment.xml',
        'views/doctor.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'reports/patient_card.xml',
        'reports/report.xml',
    ],
    'demo':[],
    'installable': True,
    'auto_install': False,
    'application': True,
}